apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - botkube
  - uptimerobot-heartbeat
  - thanos
  - promtail
  - grafana
  - loki
  - kube-prometheus-stack
  - uptime-kuma
