---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Paris
  CONFIG_CLUSTER_NAME: main
  CONFIG_K8S_POD_CIDR: 10.42.0.0/16
  NAS_ADDR: "192.168.0.18"
  NAS_PORT: "5376"
  METALLB_LB_RANGE: 192.168.10.60-192.168.10.80
  GATEWAY_ADDR: "192.168.10.1"
  METALLB_TRAEFIK_ADDR: "192.168.10.60"
  SVC_NGINX_ADDR: "192.168.10.60"
  SVC_BUILDKIT_ADDR: "192.168.10.62"
  SVC_SYSLOG_ADDR: "192.168.10.63"
  SVC_BLOCKY_ADDR: "192.168.10.64"
  SVC_HOME_ASSISTANT_ADDR: "192.168.10.65"
  SVC_ADGUARD_ADDRESS: "192.168.10.66"
  SVC_ADGUARD_ADDRESS_2: "192.168.10.67"
  SVC_PLEX_ADDR: "192.168.10.68"
  SVC_MOSQUITO_ADDR: "192.168.10.69"
  SVC_GITEA_ADDRESS: "192.168.10.70"
  SVC_CODE_ADDR: "192.168.10.71"
  SVC_EMQX_ADDR: "192.168.10.72"
  CLUSTER_LB_LOKI_SYSLOG: "192.168.10.73"
  GITLAB_LB_IP: "192.168.10.74"
