---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.0.60-192.168.0.70
  METALLB_TRAEFIK_ADDR: "192.168.0.60"
  GATEWAY_ADDR: "192.168.0.254"
  NAS_ADDR: "192.168.0.18"
  NAS_PORT: "5376"
  SVC_BLOCKY_ADDR: "192.168.0.63"
  SVC_SYSLOG_ADDR: "192.168.0.61"
  SVC_HOME_ASSISTANT_ADDR: "192.168.0.65"
  SVC_EMQX_ADDR: "192.168.0.64"
  SVC_NGINX_ADDR: "192.168.0.60"
