apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  #  - traefik
  - rook-ceph
 # - velero
  - kube-prometheus-stack
  - external-dns
  - external-snapshotter
  - starboard
