apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - system-upgrade
  - monitoring
  - flux-system
  - home
  - database
  - dev
  # - harbor
  - media
  - cert-manager
