apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - metallb-system.yaml
  - networking.yaml
  - monitoring-namespace.yaml
  - rook-ceph.yaml
  - tools.yaml
  - velero.yaml
  - home.yaml
  - security.yaml
